-- MySQL Script generated by MySQL Workbench
-- Tue May 17 11:42:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ERP
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ERP` ;

-- -----------------------------------------------------
-- Schema ERP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ERP` DEFAULT CHARACTER SET utf8 ;
USE `ERP` ;

-- -----------------------------------------------------
-- Table `ERP`.`Empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP`.`Empleados` ;

CREATE TABLE IF NOT EXISTS `ERP`.`Empleados` (
  `idEmpleados` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(10) NOT NULL,
  `CURP` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NULL,
  `Puesto` VARCHAR(45) NOT NULL,
  `Jornada` VARCHAR(45) NOT NULL,
  `FechaDeIngreso` DATE NOT NULL,
  `NSS` VARCHAR(10) NOT NULL,
  `pw` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`idEmpleados`),
  UNIQUE INDEX `idEmpleados_UNIQUE` (`idEmpleados` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ERP`.`PNS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP`.`PNS` ;

CREATE TABLE IF NOT EXISTS `ERP`.`PNS` (
  `idPNS` INT NOT NULL AUTO_INCREMENT,
  `Vacaciones` FLOAT NULL,
  `Transporte` FLOAT NULL DEFAULT 0,
  `GastosMaterial` FLOAT ZEROFILL NULL DEFAULT 0,
  `Complementos` FLOAT ZEROFILL NULL DEFAULT 0,
  `C_Gasto` VARCHAR(45) NULL DEFAULT '\"\"',
  `C_Complemento` VARCHAR(45) NULL DEFAULT '\"\"',
  `C_Transporte` VARCHAR(45) NULL DEFAULT '\"\"',
  `FidEmpleados` INT NOT NULL,
  PRIMARY KEY (`idPNS`),
  INDEX `fk_PNS_Empleados1_idx` (`FidEmpleados` ASC) ,
  CONSTRAINT `fk_PNS_Empleados1`
    FOREIGN KEY (`FidEmpleados`)
    REFERENCES `ERP`.`Empleados` (`idEmpleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ERP`.`PS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP`.`PS` ;

CREATE TABLE IF NOT EXISTS `ERP`.`PS` (
  `idPS` INT NOT NULL AUTO_INCREMENT,
  `Sueldo_Base` FLOAT NOT NULL,
  `HorasExtras` FLOAT NULL,
  `Vales_Despensa` FLOAT NULL,
  `Festivo_laborado` FLOAT NULL,
  `HORAS_TOTALES` FLOAT NULL,
  `FidEmpleados` INT NOT NULL,
  PRIMARY KEY (`idPS`),
  INDEX `fk_PS_Empleados1_idx` (`FidEmpleados` ASC) ,
  CONSTRAINT `fk_PS_Empleados1`
    FOREIGN KEY (`FidEmpleados`)
    REFERENCES `ERP`.`Empleados` (`idEmpleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ERP`.`Deducciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP`.`Deducciones` ;

CREATE TABLE IF NOT EXISTS `ERP`.`Deducciones` (
  `idDeducciones` INT NOT NULL AUTO_INCREMENT,
  `IRPF` FLOAT NULL DEFAULT 1.92,
  `IMSS` FLOAT NULL DEFAULT 7.2,
  `ISR` FLOAT NULL DEFAULT 25,
  `FidPS` INT NOT NULL,
  PRIMARY KEY (`idDeducciones`),
  INDEX `fk_Deducciones_Percepciones1_idx` (`FidPS` ASC) ,
  CONSTRAINT `fk_Deducciones_Percepciones1`
    FOREIGN KEY (`FidPS`)
    REFERENCES `ERP`.`PS` (`idPS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ERP`.`Horas trabajadas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP`.`Horas trabajadas` ;

CREATE TABLE IF NOT EXISTS `ERP`.`Horas trabajadas` (
  `H. de entrada` INT NOT NULL,
  `H. de salida` VARCHAR(45) NULL,
  `Horas trabajadascol` VARCHAR(45) NULL,
  PRIMARY KEY (`H. de entrada`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ERP`.`Dia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP`.`Dia` ;

CREATE TABLE IF NOT EXISTS `ERP`.`Dia` (
  `idDia` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `H_Entrada` TIME NULL,
  `H_Salida` TIME NULL,
  `H_Normales` FLOAT NULL,
  `FidEmpleados` INT NOT NULL,
  `Rentrada` TINYINT(1) NULL DEFAULT 0,
  `Rsalida` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`idDia`),
  INDEX `fk_Dia_Empleados1_idx` (`FidEmpleados` ASC) ,
  CONSTRAINT `fk_Dia_Empleados1`
    FOREIGN KEY (`FidEmpleados`)
    REFERENCES `ERP`.`Empleados` (`idEmpleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ERP`.`Incentivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP`.`Incentivos` ;

CREATE TABLE IF NOT EXISTS `ERP`.`Incentivos` (
  `idIncentivos` INT NOT NULL AUTO_INCREMENT,
  `Incentivo` FLOAT NULL DEFAULT 0,
  `concepto` VARCHAR(45) NULL DEFAULT '\"\"',
  `FidPS` INT NOT NULL,
  PRIMARY KEY (`idIncentivos`),
  INDEX `fk_Incentivos_PS1_idx` (`FidPS` ASC) ,
  CONSTRAINT `fk_Incentivos_PS1`
    FOREIGN KEY (`FidPS`)
    REFERENCES `ERP`.`PS` (`idPS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ERP`.`Indemnizaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP`.`Indemnizaciones` ;

CREATE TABLE IF NOT EXISTS `ERP`.`Indemnizaciones` (
  `idIndemnizaciones` INT NOT NULL AUTO_INCREMENT,
  `indemnizacion` FLOAT NULL DEFAULT 0,
  `Concepto` VARCHAR(45) NULL DEFAULT '\"\"',
  `FidPNS` INT NOT NULL,
  PRIMARY KEY (`idIndemnizaciones`),
  INDEX `fk_Indemnizaciones_PNS1_idx` (`FidPNS` ASC) ,
  CONSTRAINT `fk_Indemnizaciones_PNS1`
    FOREIGN KEY (`FidPNS`)
    REFERENCES `ERP`.`PNS` (`idPNS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ERP`.`Prestamo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ERP`.`Prestamo` ;

CREATE TABLE IF NOT EXISTS `ERP`.`Prestamo` (
  `idPrestamo` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `Cantidad` FLOAT NOT NULL DEFAULT 0,
  `CobroQuincenal` FLOAT NOT NULL DEFAULT 0,
  `Concepto` VARCHAR(45) NOT NULL DEFAULT '\"\"',
  `FidEmpleados` INT NOT NULL,
  PRIMARY KEY (`idPrestamo`),
  INDEX `fk_Prestamo_Empleados1_idx` (`FidEmpleados` ASC) ,
  CONSTRAINT `fk_Prestamo_Empleados1`
    FOREIGN KEY (`FidEmpleados`)
    REFERENCES `ERP`.`Empleados` (`idEmpleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
